### ISSUE TITLE
Getting this issue on my toons that have their artifacts

### ISSUE THREAD

**Issue by Thrumbar** [Mirroar/TopFit#65]
TopFit: [Titanstrile] could not be found in you inventory for equiping! Did you remove it from calculation ?

Same on my mage with ebonchill...

**Comment by ckaotik** [comment]
Seems Blizzard changed how `GetItemInfo` handles artifact links. Should be fixed with 6cbec9f.

**Comment by Thrumbar** [comment]
May have to use GetArtifactInfo() for artifacts and GetItemInfo() for everything else...

**Comment by Thrumbar** [comment]
1 	itemName 	String 	The name of the item.
2 	itemLink 	String 	The item link of the item.
3 	itemRarity 	Number 	The quality of the item. The value is 0 to 7, which represents Poor to Heirloom. This appears to include gains from upgrades/bonuses.
4 	itemLevel 	Number 	The item level of this item, not including item levels gained from upgrades. There is currently no API to get the item level including upgrades/bonuses.
5 	itemMinLevel 	Number 	The minimum level required to use the item, 0 meaning no level requirement.
6 	itemType 	String 	The type of the item: Armor, Weapon, Quest, Key, etc.
7 	itemSubType 	String 	The sub-type of the item: Enchanting, Cloth, Sword, etc. See itemType.
8 	itemStackCount 	Number 	How many of the item per stack: 20 for Runecloth, 1 for weapon, 100 for Alterac Ram Hide, etc.
9 	itemEquipLoc 	String 	The type of inventory equipment location in which the item may be equipped, or "" if it can't be equippable. The string returned is also the name of a global string variable e.g. if "INVTYPE_WEAPONMAINHAND" is returned, _G["INVTYPE_WEAPONMAINHAND"] will be the localized, displayable name of the location.
10 	iconFileDataID 	Number 	The FileDataID for the icon texture for the item.
11 	itemSellPrice 	Number 	The price, in copper, a vendor is willing to pay for this item, 0 for items that cannot be sold.
12 	itemClassID 	Number 	This is the numerical value that determines the string to display for 'itemType'.
13 	itemSubClassID 	Number 	This is the numerical value that determines the string to display for 'itemSubType'
14 	bindType 	Number
15 	expacID 	Number
16 	itemSetID 	Number
17 	isCraftingReagent 	Boolean
