### ISSUE TITLE
TopFit: [Tender Hjarta Loop] could not be found in your inventory for equipping! Did you remove it during calculation?

### ISSUE THREAD

**Issue by Thrumbar** [Mirroar/TopFit#66]
Getting this even though it is equipped..

TopFit: [Tender Hjarta Loop] could not be found in your inventory for equipping! Did you remove it during calculation?

**Comment by ckaotik** [comment]
I've also encountered this a bunch of times. No idea yet how it's triggered, and thus can't fix it. As a workaround, you can unequip the item and run calculations again, that usually fixes it.
